services:
  prometheus:
    image: prom/prometheus:v3.7.3
    container_name: prometheus
    volumes:
      - "./config/prometheus-config.yml:/etc/prometheus/prometheus.yml"
    networks:
      - spring-ai
    ports:
      - "9090:9090"
  grafana:
    image: grafana/grafana:main-ubuntu
    container_name: grafana
    volumes:
      - grafana-storage:/var/lib/grafana
    networks:
      - spring-ai
    ports:
      - "3000:3000"

networks:
  spring-ai:
    driver: bridge

volumes:
  grafana-storage: